server:
  http_listen_port: 19080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:11100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: job
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_name]
        target_label: container_name
      - source_labels: [__meta_docker_container_name]
        target_label: __path__
        replacement: "/var/lib/docker/containers/${1}/*.log"