receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  debug:
  otlp:
    endpoint: jaeger:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]