version: "3"

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ../configs/telemetry.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "55680:55680" # OpenTelemetry Metrics
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Collector HTTP API
      - "14250:14250" # gRPC для OTLP
      - "14317:4317"   # OTLP gRPC (если отправлять напрямую в Jaeger)
    networks:
      - monitoring

networks:
  monitoring: